"""Realtime monitor router: thin HTTP/WebSocket bindings over realtime_runtime services."""
from __future__ import annotations

from fastapi import APIRouter

from backend.realtime_runtime import diagnostics_service, pool_service, ws_gateway

router = APIRouter()

router.get("/tick_provider")(pool_service.tick_provider_info)
router.get("/ui_config")(pool_service.realtime_ui_config)
router.get("/pool/1/observe_stats")(pool_service.pool1_observe_stats)
router.get("/pool/1/position_summary")(pool_service.pool1_position_summary)
router.get("/pool/1/decision_summary")(pool_service.pool1_decision_summary)
router.post("/refresh_daily_cache")(pool_service.refresh_daily_cache)
router.get("/pools")(pool_service.list_pools)
router.get("/concept_boards")(pool_service.list_concept_boards)
router.get("/concept_fund_flow")(pool_service.list_concept_fund_flow)
router.get("/market_changes")(pool_service.list_market_changes)
router.get("/news_feed")(pool_service.list_news_feed)
router.get("/concept_board/members")(pool_service.get_concept_board_members)
router.get("/pool/{pool_id}/members")(pool_service.get_members)
router.post("/pool/{pool_id}/add")(pool_service.add_member)
router.delete("/pool/{pool_id}/remove/{ts_code}")(pool_service.remove_member)
router.put("/pool/{pool_id}/note/{ts_code}")(pool_service.update_note)
router.get("/pool/{pool_id}/signals_fast")(pool_service.evaluate_signals_fast)
router.get("/pool/{pool_id}/signals")(pool_service.evaluate_signals)
router.post("/batch/tick")(pool_service.batch_tick)
router.post("/batch/minute")(pool_service.batch_minute)
router.post("/batch/transactions")(pool_service.batch_transactions)
router.get("/tick/{ts_code}")(pool_service.get_tick)
router.get("/minute/{ts_code}")(pool_service.get_minute)
router.get("/transactions/{ts_code}")(pool_service.get_transactions)
router.get("/market_status")(pool_service.market_status)
router.get("/indices")(pool_service.indices)
router.get("/pool/{pool_id}/signal_history")(pool_service.get_signal_history)
router.get("/pool/2/quality_summary")(pool_service.get_t0_quality_summary)
router.get("/pool/2/drift_status")(pool_service.get_t0_drift_status)
router.get("/runtime/t0_reverse_replay")(diagnostics_service.runtime_t0_reverse_replay)
router.get("/runtime/db_metrics")(diagnostics_service.runtime_db_metrics)
router.get("/runtime/t0_quality_live")(diagnostics_service.runtime_t0_quality_live)
router.get("/runtime/threshold_calibration_snapshot")(diagnostics_service.runtime_threshold_calibration_snapshot)
router.get("/runtime/selfcheck")(diagnostics_service.runtime_selfcheck)
router.get("/runtime/channel_split_stats")(diagnostics_service.runtime_channel_split_stats)
router.get("/runtime/fast_slow_diff")(diagnostics_service.runtime_fast_slow_diff)
router.get("/runtime/t0_reverse_diagnostics")(diagnostics_service.runtime_t0_reverse_diagnostics)
router.get("/runtime/consistency_check")(diagnostics_service.runtime_consistency_check)
router.get("/runtime/fast_slow_trend")(diagnostics_service.runtime_fast_slow_trend)
router.get("/runtime/health_summary")(diagnostics_service.runtime_health_summary)
router.get("/runtime/health_pressure")(diagnostics_service.runtime_health_pressure)
router.get("/runtime/health_alerts")(diagnostics_service.runtime_health_alerts)
router.websocket("/ws")(ws_gateway.realtime_ws)
